### ISSUE TITLE
Serverside Crash due to ldlib (Possible)

### ISSUE THREAD

**Issue by DSRLIN** [GregTechCEu/GregTechCEu-1.19#1090]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.0-build584

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Sky-Greg

### Expected Behavior

Open single block machine

### Actual Behavior

Server crashes.

### Steps to Reproduce

1. Update to newest version of GregTechCEu.
2. Open a single block machine.

### Additional Information

Seems this behavior is due to ldlib.
Crash report:
java.lang.ExceptionInInitializerError: null
        at com.lowdragmc.lowdraglib.emi.EMIPlugin.isEmiEnabled(EMIPlugin.java:32) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading}
        at com.lowdragmc.lowdraglib.LDLib.isEmiLoaded(LDLib.java:81) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,re:mixin}
        at com.lowdragmc.lowdraglib.LDLib.isJeiLoaded(LDLib.java:73) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,re:mixin}
        at com.gregtechceu.gtceu.api.recipe.ui.GTRecipeTypeUI.lambda$createEditableUITemplate$8(GTRecipeTypeUI.java:220) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.gui.editor.IEditableUI$Normal.setupUI(IEditableUI.java:28) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.machine.SimpleTieredMachine.lambda$static$2(SimpleTieredMachine.java:375) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.gui.editor.EditableMachineUI.setupUI(EditableMachineUI.java:51) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.machine.feature.IFancyUIMachine.createMainPage(IFancyUIMachine.java:52) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.gui.fancy.FancyMachineUIWidget.setupFancyUI(FancyMachineUIWidget.java:196) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.gui.fancy.FancyMachineUIWidget.performNavigation(FancyMachineUIWidget.java:135) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.gui.fancy.FancyMachineUIWidget.initWidget(FancyMachineUIWidget.java:90) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.initWidget(WidgetGroup.java:349) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,pl:runtimedistcleaner:A}
        at com.lowdragmc.lowdraglib.gui.modular.ModularUI.initWidgets(ModularUI.java:205) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,pl:runtimedistcleaner:A}
        at com.lowdragmc.lowdraglib.gui.factory.UIFactory.openUI(UIFactory.java:41) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,pl:runtimedistcleaner:A}
        at com.gregtechceu.gtceu.api.machine.feature.IUIMachine.tryToOpenUI(IUIMachine.java:26) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.block.MetaMachineBlock.m_6227_(MetaMachineBlock.java:289) ~[gtceu-1.20.1-1.2.0-build_584.jar%23405!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:778) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:framedblocks.mixin.json:MixinBlockStateBase,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:libx:interact,re:classloading,pl:accesstransformer:B,xf:fml:libx:interact}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:forgivingvoid.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:APP:badpackets.mixins.json:MixinServerGamePacketListenerImpl,pl:mixin:APP:littletiles.mixins.json:server.network.ServerGamePacketListenerImplAccessor,pl:mixin:APP:littletiles.mixins.json:server.network.ServerGamePacketListenerImplMixin,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.lang.NullPointerException: Cannot invoke "dev.emi.emi.platform.EmiAgnos.isForgeAgnos()" because "dev.emi.emi.platform.EmiAgnos.delegate" is null
        at dev.emi.emi.platform.EmiAgnos.isForge(EmiAgnos.java:34) ~[emi-1.1.4+1.20.1+forge.jar%23370!/:?] {re:classloading}
        at dev.emi.emi.config.EmiConfig.<clinit>(EmiConfig.java:105) ~[emi-1.1.4+1.20.1+forge.jar%23370!/:?] {re:classloading}
        ... 35 more

**Comment by DSRLIN** [comment]
Game version 1.20.1

**Comment by screret** [comment]
do you have EMI installed or not? the game thinks EMI is installed but then it can't find the EMI side-specific thing

**Comment by DSRLIN** [comment]
Yes, both client and server have installed the EMI.

**Comment by DSRLIN** [comment]
Fixed in ldlib 1.0.25-e.
