### ISSUE TITLE
server error while starting

### ISSUE THREAD

**Issue by IceFoxyy** [GregTechCEu/GregTechCEu-1.19#1278]
### Checked for existing issues

- [ ] I have checked for existing issues, and have found none.

### Tested latest version

- [ ] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.2.a

### Recipe Viewer Installed

JEI

### Environment

server console

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ATM9

### Expected Behavior

start the world without crash

### Actual Behavior

the Server crashes with the following error:
```
[main/ERROR] [net.minecraftforge.fml.DeferredWorkQueue/]: Mod 'gtceu' encountered an error in a deferred task:
java.lang.IllegalStateException: missing pattern while creating multiblock star_forge
	at com.gregtechceu.gtceu.api.registry.registrate.MultiblockMachineBuilder.register(MultiblockMachineBuilder.java:352) ~[gtceu-1.20.1-1.2.2.a.jar%23677!/:?]
	at com.gregtechceu.gtceu.api.registry.registrate.MultiblockMachineBuilder.register(MultiblockMachineBuilder.java:58) ~[gtceu-1.20.1-1.2.2.a.jar%23677!/:?]
	at com.gregtechceu.gtceu.integration.kjs.GTRegistryInfo.registerFor(GTRegistryInfo.java:152) ~[gtceu-1.20.1-1.2.2.a.jar%23677!/:?]
	at com.gregtechceu.gtceu.common.data.GTMachines.init(GTMachines.java:2203) ~[gtceu-1.20.1-1.2.2.a.jar%23677!/:?]
	at com.gregtechceu.gtceu.common.CommonProxy.init(CommonProxy.java:120) ~[gtceu-1.20.1-1.2.2.a.jar%23677!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$2(DeferredWorkQueue.java:81) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:76) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$0(DeferredWorkQueue.java:60) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:60) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at net.minecraftforge.fml.core.ParallelTransition.lambda$finalActivityGenerator$2(ParallelTransition.java:35) ~[forge-1.20.1-47.2.20-universal.jar%23914!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:43) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:28) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:224) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.20.jar%23910!/:?]
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.2.20-universal.jar%23914!/:?]
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23909!/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?]
```

### Steps to Reproduce

i tried launching the server first time with version 1.2.2.a

### Additional Information

downgrading to 1.2.0.a works server sided but makes the client crash

**Comment by screret** [comment]
ATM9/Gravitas2 issue.
