### ISSUE TITLE
Unable to join the world

### ISSUE THREAD

**Issue by gateguardian523** [GregTechCEu/GregTechCEu-1.19#1392]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a-build_753

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

KubeJS, Rhino, Architectury API

### Expected Behavior

Joining the world

### Actual Behavior

<img width="1261" alt="screenshot" src="https://github.com/GregTechCEu/GregTech-Modern/assets/147252672/27d9f7fe-aff1-404b-8a0c-3f9aefa0df6c">

### Steps to Reproduce

1. Create a custom material.
```
GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('lignite')
        .gem(1, 1200).ore(2, 1).color(0x513939)
        .iconSet(GTMaterialIconSet.LIGNITE)
        .flags(GTMaterialFlags.FLAMMABLE, GTMaterialFlags.NO_SMASHING, GTMaterialFlags.MORTAR_GRINDABLE)
        .components('3x carbon', '1x water')
})
```

2. Create ore vein using custom material.
```
GTCEuServerEvents.oreVeins(event => {
    event.add('kubejs:coal', vein => {
        vein.weight(80)
        vein.clusterSize(60)
        vein.density(1.3)

        vein.layer('stone')
        vein.dimensions("minecraft:overworld")
        vein.biomes("#minecraft:is_overworld")

        vein.heightRangeUniform(-20, 80)

        vein.veinedVeinGenerator(generator => generator
            .oreBlock(GTMaterials.Coal, 3)
            .rareBlock(GTMaterials.get('lignite'), 1)
            .rareBlockChance(0.2)
            .veininessThreshold(0.1)
            .maxRichnessThreshold(0.175)
            .minRichness(0.4)
            .maxRichness(0.7)
            .edgeRoundoffBegin(3)
            .maxEdgeRoundoff(0.1)
        )
        vein.surfaceIndicatorGenerator(indicator => indicator
            .surfaceRock(GTMaterials.Coal)
            .placement("above")
        )
    })
})
```

3. Create a world and join

### Additional Information

[096��2024 19:27:15.318] [Server thread/ERROR] [GregTechCEu/]: Value 1.3 outside of range [0.0:1.0]
[096��2024 19:27:15.321] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Value 1.3 outside of range [0.0:1.0]
	Index: 4
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$4703/0x000001dfe8c72450@7171480b
		4: ASM: class com.gregtechceu.gtceu.forge.ForgeCommonEventListener onPlayerJoinServer(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		6: ASM: net.minecraftforge.common.ForgeInternalHandler@39a398a4 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.RuntimeException: Value 1.3 outside of range [0.0:1.0]
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Right.map(Either.java:99)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
	at TRANSFORMER/gtceu@1.2.3.a-build_753/com.gregtechceu.gtceu.common.network.packets.SPacketSyncOreVeins.encode(SPacketSyncOreVeins.java:40)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.network.simple.SimpleChannel.sendTo(SimpleChannel.java:92)
	at TRANSFORMER/ldlib@1.0.25.m/com.lowdragmc.lowdraglib.networking.forge.Networking.sendToPlayer(Networking.java:107)
	at TRANSFORMER/gtceu@1.2.3.a-build_753/com.gregtechceu.gtceu.forge.ForgeCommonEventListener.onPlayerJoinServer(ForgeCommonEventListener.java:207)
	at TRANSFORMER/gtceu@1.2.3.a-build_753/com.gregtechceu.gtceu.forge.__ForgeCommonEventListener_onPlayerJoinServer_PlayerLoggedInEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)

[096��2024 19:27:15.322] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
java.lang.RuntimeException: Value 1.3 outside of range [0.0:1.0]
	at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101) ~[datafixerupper-6.0.8.jar%2393!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar%2393!/:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-6.0.8.jar%2393!/:?]
	at com.gregtechceu.gtceu.common.network.packets.SPacketSyncOreVeins.encode(SPacketSyncOreVeins.java:40) ~[gtceu-1.20.1-1.2.3.a-build_753.jar%23162!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.sendTo(SimpleChannel.java:92) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at com.lowdragmc.lowdraglib.networking.forge.Networking.sendToPlayer(Networking.java:107) ~[ldlib-forge-1.20.1-1.0.25.m.jar%23181!/:?]
	at com.gregtechceu.gtceu.forge.ForgeCommonEventListener.onPlayerJoinServer(ForgeCommonEventListener.java:207) ~[gtceu-1.20.1-1.2.3.a-build_753.jar%23162!/:?]
	at com.gregtechceu.gtceu.forge.__ForgeCommonEventListener_onPlayerJoinServer_PlayerLoggedInEvent.invoke(.dynamic) ~[gtceu-1.20.1-1.2.3.a-build_753.jar%23162!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[096��2024 19:27:15.323] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: qwer lost connection: Invalid player data

**Comment by screret** [comment]
a vein's density can't be >1.
Look at line 5 of your vein script.

**Comment by gateguardian523** [comment]
My bad, thank you.
