### ISSUE TITLE
failed to synchronize bedrock fluid veins

### ISSUE THREAD

**Issue by ianfd** [GregTechCEu/GregTechCEu-1.19#1816]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.0

### Minecraft Version

1.21

### Recipe Viewer Installed

JEI

### Environment

Multiplayer

### Cross-Mod Interaction

No

### Other Installed Mods

None

### Expected Behavior

Normal join onto the server

### Actual Behavior

The join process crashes. I'm unable to join the server, this happens, when the loading terrain text occurs on the screen. 

This is the connection crash log.

`---- Minecraft Network Protocol Error Report ----
// I'm sorry, I don't speak that language

Time: 2024-08-25 01:26:32
Description: Packet handling error

io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:custom_payload'
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:38) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:14) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:31) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar%23121!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar%23121!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar%23121!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%2398!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%2398!/:4.1.97.Final] {}
	at java.base/java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
Caused by: java.lang.RuntimeException: Failed decoding custom payload gtceu:sync_bedrock_fluid_veins: java.lang.IllegalStateException: Not a list: "#minecraft:is_ocean"; Can't access registry ResourceKey[minecraft:root / minecraft:worldgen/biome]; Can't access registry ResourceKey[minecraft:root / minecraft:worldgen/biome]; Can't access registry ResourceKey[minecraft:root / minecraft:worldgen/biome]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:55) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	... 45 more
Caused by: java.lang.IllegalStateException: Not a list: "#minecraft:is_ocean"; Can't access registry ResourceKey[minecraft:root / minecraft:worldgen/biome]; Can't access registry ResourceKey[minecraft:root / minecraft:worldgen/biome]; Can't access registry ResourceKey[minecraft:root / minecraft:worldgen/biome]
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23111!/:?] {}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23111!/:?] {}
	at TRANSFORMER/gtceu@1.4.0/com.gregtechceu.gtceu.common.network.packets.SPacketSyncFluidVeins.lambda$decode$0(SPacketSyncFluidVeins.java:57) ~[gtceu-1.21.1-1.4.0.jar%23257!/:?] {re:classloading}
	at java.base/java.util.stream.StreamSpliterators$InfiniteSupplyingSpliterator$OfRef.tryAdvance(Unknown Source) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?] {}
	at TRANSFORMER/gtceu@1.4.0/com.gregtechceu.gtceu.common.network.packets.SPacketSyncFluidVeins.decode(SPacketSyncFluidVeins.java:59) ~[gtceu-1.21.1-1.4.0.jar%23257!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$2.decode(StreamCodec.java:37) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:53) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Client IO #3
Stacktrace:
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.PacketListener.fillCrashReport(PacketListener.java:33) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading,re:mixin}
-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: neoforge
Stacktrace:
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.PacketListener.fillCrashReport(PacketListener.java:33) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.PacketUtils.fillCrashReport(PacketUtils.java:62) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl.storeDisconnectionReport(ClientCommonPacketListenerImpl.java:130) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl.createDisconnectionInfo(ClientCommonPacketListenerImpl.java:123) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.Connection.exceptionCaught(Connection.java:157) ~[client-1.21-20240613.152323-srg.jar%23237!/:?] {re:classloading,re:mixin}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar%23121!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar%23121!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar%23167!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar%23121!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar%23139!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%2398!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%2398!/:4.1.97.Final] {}
	at java.base/java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.`

### Steps to Reproduce

Use GTCEu at 1.21.-1.4.0 and NeoForge version 21.0.167 for 1.21.

**Comment by YoungOnionMC** [comment]
fixed in #1918
