### ISSUE TITLE
Non [a-z0-9/._-] character in path of location

### ISSUE THREAD

**Issue by TankTopGorilla** [GregTechCEu/GregTechCEu-1.19#1960]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.2 Build 1100 Snapshot

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

First Time Opening the Game

### Cross-Mod Interaction

Yes

### Other Installed Mods

ATM9

### Expected Behavior

Expected to Game to launch properly

### Actual Behavior

Game did not launch.

### Steps to Reproduce

I did try to open the game after installing ATM9, it gave the same error with default installation. I updated to latest snapshot incase you guys have fixed it but no. Still does not open.

### Additional Information

	Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: gtceu:empty_t\u0131er_\u0131_battery
		at net.minecraft.resources.ResourceLocation.m_245185_(ResourceLocation.java:236) ~[client-1.20.1-20230612.114412-srg.jar%23996!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:mixins.oculus.json:texture.MixinResourceLocation,pl:mixin:A}
		at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23996!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:mixins.oculus.json:texture.MixinResourceLocation,pl:mixin:A}
		at com.tterrag.registrate.AbstractRegistrate.accept(AbstractRegistrate.java:884) ~[Registrate-MC1.20-1.3.11.jar%231100!/:?] {re:mixin,re:classloading,pl:mixin:A}
		at com.gregtechceu.gtceu.api.registry.registrate.GTRegistrate.accept(GTRegistrate.java:196) ~[gtceu-1.20.1-1.4.2-build_1100-SNAPSHOT.jar%23763!/:1.4.2-SNAPSHOT] {re:classloading}
		at com.tterrag.registrate.builders.AbstractBuilder.register(AbstractBuilder.java:73) ~[Registrate-MC1.20-1.3.11.jar%231100!/:?] {re:classloading,re:mixin}
		at com.tterrag.registrate.builders.ItemBuilder.register(ItemBuilder.java:296) ~[Registrate-MC1.20-1.3.11.jar%231100!/:?] {re:classloading}
		at com.tterrag.registrate.builders.ItemBuilder.register(ItemBuilder.java:44) ~[Registrate-MC1.20-1.3.11.jar%231100!/:?] {re:classloading}
		at com.tterrag.registrate.builders.Builder.build(Builder.java:215) ~[Registrate-MC1.20-1.3.11.jar%231100!/:?] {re:classloading,re:mixin}
		at com.gregtechceu.gtceu.common.data.GTBlocks.createBatteryBlock(GTBlocks.java:901) ~[gtceu-1.20.1-1.4.2-build_1100-SNAPSHOT.jar%23763!/:1.4.2-SNAPSHOT] {re:classloading}
		at com.gregtechceu.gtceu.common.data.GTBlocks.<clinit>(GTBlocks.java:687) ~[gtceu-1.20.1-1.4.2-build_1100-SNAPSHOT.jar%23763!/:1.4.2-SNAPSHOT] {re:classloading}
		... 39 more

**Comment by screret** [comment]
your computer's language is turkish I assume?

**Comment by screret** [comment]
try adding `-Duser.language=en` to java launch parameters
