### ISSUE TITLE
error with c2me

### ISSUE THREAD

**Issue by coco875** [GregTechCEu/GregTechCEu-1.19#2240]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.21.1

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

c2me 0.3.0+alpha0.292, connector 2.0.0-beta.3, Chunky 1.4.16

### Expected Behavior

Generate Chunk

### Actual Behavior

Deadlock on world generation

### Steps to Reproduce

1) Create a new world
2) Run `/chunky start minecraft:overworld square 0 0 10000` (maybe less are needed it just to increase chance

### Additional Information

It's likely because threaded features from c2me because of one of multiple error in log:
```
[23oct.2024 12:32:33.306] [c2me-worker-0/ERROR] [Chunk System of minecraft:overworld/]: Error upgrading chunk [36, 20] to "minecraft:features"
net.minecraft.ReportedException: Exception generating new chunk
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.WorldGenRegion.getChunk(WorldGenRegion.java:143) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.LevelReader.getChunk(LevelReader.java:130) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.WorldGenRegion.getChunk(WorldGenRegion.java:108) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.WorldGenRegion.getHeight(WorldGenRegion.java:410) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	at TRANSFORMER/gtceu@1.4.6/com.gregtechceu.gtceu.api.worldgen.generator.indicators.SurfaceIndicatorGenerator$IndicatorPlacement.lambda$static$0(SurfaceIndicatorGenerator.java:189) ~[gtceu-1.21.1-1.4.6.jar%23194!/:?]
	at TRANSFORMER/gtceu@1.4.6/com.gregtechceu.gtceu.api.worldgen.generator.indicators.SurfaceIndicatorGenerator.lambda$createPlacer$8(SurfaceIndicatorGenerator.java:151) ~[gtceu-1.21.1-1.4.6.jar%23194!/:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at TRANSFORMER/gtceu@1.4.6/com.gregtechceu.gtceu.api.worldgen.generator.indicators.SurfaceIndicatorGenerator.lambda$createPlacer$10(SurfaceIndicatorGenerator.java:153) ~[gtceu-1.21.1-1.4.6.jar%23194!/:?]
	at TRANSFORMER/gtceu@1.4.6/com.gregtechceu.gtceu.api.worldgen.ores.OrePlacer.lambda$placeIndicators$5(OrePlacer.java:87) ~[gtceu-1.21.1-1.4.6.jar%23194!/:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at TRANSFORMER/gtceu@1.4.6/com.gregtechceu.gtceu.api.worldgen.ores.OrePlacer.placeIndicators(OrePlacer.java:86) ~[gtceu-1.21.1-1.4.6.jar%23194!/:?]
	at TRANSFORMER/gtceu@1.4.6/com.gregtechceu.gtceu.api.worldgen.ores.OrePlacer.lambda$placeOres$1(OrePlacer.java:52) ~[gtceu-1.21.1-1.4.6.jar%23194!/:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at TRANSFORMER/gtceu@1.4.6/com.gregtechceu.gtceu.api.worldgen.ores.OrePlacer.placeOres(OrePlacer.java:52) ~[gtceu-1.21.1-1.4.6.jar%23194!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.ChunkGenerator.handler$bhp000$gtceu$applyBiomeDecoration(ChunkGenerator.java:1203) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:413) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStatusTasks.generateFeatures(ChunkStatusTasks.java:154) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.apply(ChunkStep.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0alpha.0.2921.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.VanillaWorldGenerationDelegate.lambda$upgradeToThis$8(VanillaWorldGenerationDelegate.java:123) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.292$c2me-rewrites-chunk-system-mc1.21.1-0.3.0+alpha.0.292_mapped_moj_1.21.1.jar%23419!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.2921.21.1/com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.292$c2me-base-mc1.21.1-0.3.0+alpha.0.292-all_mapped_moj_1.21.1.jar%23403!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.2921.21.1/com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:57) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.292$c2me-base-mc1.21.1-0.3.0+alpha.0.292-all_mapped_moj_1.21.1.jar%23403!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.2921.21.1/com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.292$c2me-base-mc1.21.1-0.3.0+alpha.0.292-all_mapped_moj_1.21.1.jar%23403!/:?]
Caused by: java.lang.IllegalStateException: Requested chunk unavailable during world generation
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.WorldGenRegion.getChunk(WorldGenRegion.java:129) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?]
	... 29 more
[23oct.2024 12:32:33.313] [Server thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID ea734a27-3653-47f5-b70d-676f38d610ff
```

**Comment by screret** [comment]
we do not support sinytra corrector or C2ME.

**Comment by coco875** [comment]
you don't support C2me because it's a fabric mod load through connector or because of his threaded features ?

**Comment by screret** [comment]
both.

**Comment by JuiceyBeans** [comment]
> you don't support C2me because it's a fabric mod load through connector or because of his threaded features ?

Probably don't run a performance mod using Connector, use something like Moonrise instead that is NeoForge native

**Comment by coco875** [comment]
on some benchmark made c2me perfome better then moonrise and moonrise have issue with more important mod like forgematica or creativeCore https://gist.github.com/ishland/70ace806d15569d9cfea611b8a9ff90f
