### ISSUE TITLE
[1.20.1]和moshit兼容问题

### ISSUE THREAD

**Issue by Re-Aqest** [GregTechCEu/GregTechCEu-1.19#2283]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

服务器

### Cross-Mod Interaction

No

### Other Installed Mods

1

### Expected Behavior

修复bug

### Actual Behavior

1

### Steps to Reproduce

服务器一个区块重度环境污染 靠近变成透明的不渲染 后台还有大量的报错

### Additional Information

报错信息
无法将事件 InventoryMoveItemEvent 传递给
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[forge-1.20.1-47.3.11-universal.jar%23263!/:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.3.11-universal.jar%23263!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[forge-1.20.1-47.3.11-universal.jar%23263!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[forge-1.20.1-47.3.11-universal.jar%23263!/:?]
        at net.minecraftforge.items.VanillaInventoryCodeHooks.lambda$dropperInsertHook$1(VanillaInventoryCodeHooks.java:116) ~[forge-1.20.1-47.3.11-universal.jar%23263!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.items.VanillaInventoryCodeHooks.dropperInsertHook(VanillaInventoryCodeHooks.java:108) ~[forge-1.20.1-47.3.11-universal.jar%23263!/:?]
        at net.minecraft.world.level.block.DropperBlock.m_5824_(DropperBlock.java:41) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.world.level.block.DispenserBlock.m_213897_(DispenserBlock.java:111) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222963_(BlockBehaviour.java:759) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:835) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:432) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1166) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1071) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:910) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23258!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException

**Comment by screret** [comment]
we do not support mohist. Or any other hybrid server software, for the matter.
