### ISSUE TITLE
Can not work on server

### ISSUE THREAD

**Issue by windy664** [GregTechCEu/GregTechCEu-1.19#238]
### GregTech CEu Version

gtceu-fabric-1.20.1-1.0.9-build_113

### Environment

1.20.1 fabric

### Cross-Mod Interaction

Yes

### Additional Information

[21:22:27] [main/ERROR]: Failed to start the minecraft server
java.lang.IllegalArgumentException: Couldn't find registry entry for ResourceKey[minecraft:worldgen/placed_feature / gtceu:rubber_tree]
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationContextImpl.getEntry(BiomeModificationContextImpl.java:336) ~[fabric-biome-api-v1-13.0.10+b3afc78b77-760e8e2a38ba250.jar:?]
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationContextImpl$GenerationSettingsContextImpl.addFeature(BiomeModificationContextImpl.java:288) ~[fabric-biome-api-v1-13.0.10+b3afc78b77-760e8e2a38ba250.jar:?]
	at net.fabricmc.fabric.api.biome.v1.BiomeModifications.lambda$addFeature$0(BiomeModifications.java:52) ~[fabric-biome-api-v1-13.0.10+b3afc78b77-760e8e2a38ba250.jar:?]
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl$ModifierRecord.apply(BiomeModificationImpl.java:207) ~[fabric-biome-api-v1-13.0.10+b3afc78b77-760e8e2a38ba250.jar:?]
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.finalizeWorldGen(BiomeModificationImpl.java:147) ~[fabric-biome-api-v1-13.0.10+b3afc78b77-760e8e2a38ba250.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ccb000$fabric-biome-api-v1$finalizeWorldGen(MinecraftServer.java:3910) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:304) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:75) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.lambda$main$3(Main.java:225) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.spin(MinecraftServer.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:224) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]

**Comment by Yefancy** [comment]
#225

**Comment by screret** [comment]
fixed.
