### ISSUE TITLE
Unable to add ore veins to Ad Astra's Moon

### ISSUE THREAD

**Issue by vishtheshnu** [GregTechCEu/GregTechCEu-1.19#262]
### GregTech CEu Version

1.0.9

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

The ore vein specified via KubeJS scripts should spawn on the moon and be immediately picked up by max-tier prospector.

### Actual Behavior

No custom ore veins spawn on the moon.

### Steps to Reproduce

1. Installed mods:

Gregtech Modern 1.0.9
KubeJS 1902.6.1-build.337
Ad Astra 1.12.7

2. Added the following script to startup scripts:

```
GTCEuStartupEvents.registry('gtceu:world_gen_layer', event => {
    event.create('moon')
        .target(['ad_astra:moon_stone', 'minecraft:soul_soil'])
})

GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
    event.create('moon', 'ore')
        .stateSupplier(() => Block.getBlock('ad_astra:moon_stone').defaultBlockState())
        .material(Material.STONE)
        .color(MaterialColor.STONE)
        .sound(SoundType.STONE)
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
})
```

3. Added following script to server scripts:

```
GTCEuServerEvents.oreVeins(event => {
    event.add("modpack:moon_manganese_vein", vein => {
        vein.clusterSize(40)
            .weight(200)
            .layer("moon")
            .density(0.7)
            .heightRange({
                height: {
                    type: "uniform",
                    min_inclusive: {
                      absolute: 60
                    },
                    max_inclusive: {
                      absolute: 256
                    }
                }
            })
            .discardChanceOnAirExposure(0)
            .addSpawnDimension("ad_astra:moon")
            .addSpawnBiome({"type": "forge:any"})
            .generator(vein.generatorBuilder("gtceu:layer")
                .withLayerPattern(() => GTLayerPattern.builder([['ad_astra:moon_stone', 'minecraft:soul_soil']])
                    .layer(l => l.weight(3).mat(GTMaterials.Grossular).size(2, 2))
                    .layer(l => l.weight(3).mat(GTMaterials.Pyrolusite).size(2, 2))
                    .layer(l => l.weight(1).mat(GTMaterials.Pyrochlore).size(1, 3))
                    .layer(l => l.weight(1).mat(GTMaterials.Tantalite).size(1, 3))
                    .build()))
    })
})
```

4. On startup, create new world, teleport to the moon via command: `/execute in ad_astra:moon run teleport @p ~ 120 ~`
5. Give self prospector, see that there are no custom ores on the moon.

### Additional Information

It's likely I'm missing something in my KubeJS script, but if we can figure it out, I can contribute what I've learned as documentation to the project :)

**Comment by screret** [comment]
KubeJS log?

**Comment by vishtheshnu** [comment]
I found this relevant error in latest log that doesn't appear when I call /reload:
```
[03Aug2023 00:38:12.189] [Render thread/ERROR] [GregTechCEu/]: Registry is already frozen (requested key: ResourceKey[minecraft:dimension_type / ad_astra:moon]); Not a JSON object: "ad_astra:moon"
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: Error occurred while handling event 'GTCEuServerEvents.oreVeins': java.lang.RuntimeException: Registry is already frozen (requested key: ResourceKey[minecraft:dimension_type / ad_astra:moon]); Not a JSON object: "ad_astra:moon"
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: java.lang.RuntimeException: Registry is already frozen (requested key: ResourceKey[minecraft:dimension_type / ad_astra:moon]); Not a JSON object: "ad_astra:moon"
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100)
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.datafixers.util.Either$Right.map(Either.java:99)
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/gtceu@1.0.9/com.gregtechceu.gtceu.integration.kjs.builders.OreVeinBuilderJS.build(OreVeinBuilderJS.java:69)
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/gtceu@1.0.9/com.gregtechceu.gtceu.integration.kjs.builders.OreVeinBuilderJS.generatorBuilder(OreVeinBuilderJS.java:62)
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03Aug2023 00:38:12.189] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:1086)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:423)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:129)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:88)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:70)
[03Aug2023 00:38:12.190] [Render thread/ERROR] [KubeJS Server/]: 	at jdk.proxy1/jdk.proxy1.$Proxy139.accept(Unknown Source)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/gtceu@1.0.9/com.gregtechceu.gtceu.integration.kjs.events.GTOreVeinEventJS.add(GTOreVeinEventJS.java:19)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:1086)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:423)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.Context.doTopCall(Context.java:1197)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:2619)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:129)
[03Aug2023 00:38:12.191] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:88)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/rhino@1902.2.2-build.268/dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:70)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/jdk.proxy4/jdk.proxy4.$Proxy91.onEvent(Unknown Source)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/kubejs@1902.6.1-build.337/dev.latvian.mods.kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/kubejs@1902.6.1-build.337/dev.latvian.mods.kubejs.event.EventHandler.postToHandlers(EventHandler.java:302)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/kubejs@1902.6.1-build.337/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:272)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/kubejs@1902.6.1-build.337/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:226)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/kubejs@1902.6.1-build.337/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:189)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/gtceu@1.0.9/com.gregtechceu.gtceu.data.loader.OreDataLoader$RunKJSEventInSeparateClassBecauseForgeIsDumb.fireKJSEvent(OreDataLoader.java:81)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/gtceu@1.0.9/com.gregtechceu.gtceu.data.loader.OreDataLoader.apply(OreDataLoader.java:61)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/gtceu@1.0.9/com.gregtechceu.gtceu.data.loader.OreDataLoader.m_5787_(OreDataLoader.java:28)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[03Aug2023 00:38:12.192] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.14/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
[03Aug2023 00:38:12.193] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
[03Aug2023 00:38:12.194] [Render thread/ERROR] [KubeJS Server/]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
[03Aug2023 00:38:24.311] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:recipes_gt_to_create.js in 0.003 s
[03Aug2023 00:38:24.312] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:hammer.js in 0.0 s
[03Aug2023 00:38:24.312] [Render thread/INFO] [KubeJS Server/]: server_scripts:ore_gen_moon.js:1: Loaded Java class 'com.gregtechceu.gtceu.api.data.chemical.ChemicalHelper'
[03Aug2023 00:38:24.312] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:ore_gen_moon.js in 0.0 s
[03Aug2023 00:38:24.313] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:recipes_create.js in 0.001 s
[03Aug2023 00:38:24.314] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:recipes_early_game.js in 0.0 s
[03Aug2023 00:38:24.314] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:recipes_sequencedassembly_custom.js in 0.0 s
[03Aug2023 00:38:24.315] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:recipe_wrapper.js in 0.001 s
[03Aug2023 00:38:24.315] [Render thread/INFO] [KubeJS Server/]: server_scripts:script.js:3: Hello, World! (You will see this line every time server resources reload)
[03Aug2023 00:38:24.315] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:script.js in 0.0 s
[03Aug2023 00:38:24.316] [Render thread/INFO] [KubeJS Server/]: Loaded script server_scripts:tags.js in 0.0 s
[03Aug2023 00:38:24.316] [Render thread/INFO] [KubeJS Server/]: Loaded 9/9 KubeJS server scripts in 0.016 s
[03Aug2023 00:38:24.316] [Render thread/INFO] [KubeJS Server/]: Scripts loaded
[03Aug2023 00:38:24.316] [Render thread/INFO] [KubeJS Server/]: Initializing recipe event...
[03Aug2023 00:38:24.316] [Render thread/WARN] [KubeJS Server/]: Due to the way Minecraft resource loading works, KubeJS' server.log may not contain everything that happened in your server scripts on initial world creation.
[03Aug2023 00:38:24.316] [Render thread/WARN] [KubeJS Server/]: You can still see the full log (including past reloads) in your latest.log file.
[03Aug2023 00:38:24.419] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Starting integrated minecraft server version 1.19.2
```

server.txt
```
[00:38:23] [INIT] KubeJS 1902.6.1-build.337; MC 1902 forge
[00:38:23] [INIT] Loaded plugins:
[00:38:23] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgePlugin
[00:38:23] [INIT] - pro.mikey.kubeutils.kubejs.KubeUtilsPlugin
[00:38:23] [INIT] - com.almostreliable.ponderjs.PonderJSPlugin
[00:38:23] [INIT] - com.bobvarioa.kubejsreiruntime.integrations.kube.KubePlugin
[00:38:23] [INIT] - com.gregtechceu.gtceu.integration.kjs.GregTechKubeJSPlugin
[00:38:23] [INIT] - com.oierbravo.createmechanicalextruder.compat.kubejs.KubeJSCreateMechanicalExtruderPlugin
[00:38:23] [INIT] - dev.latvian.mods.kubejs.create.KubeJSCreatePlugin
[00:38:23] [INIT] - com.almostreliable.lootjs.kube.LootJSPlugin
[00:38:23] [INIT] - com.lowdragmc.lowdraglib.kjs.LDLibKubeJSPlugin
[00:38:23] [INIT] - com.probejs.ProbeJSPlugin
[00:38:24] [INFO] Loaded script server_scripts:recipes_gt_to_create.js in 0.003 s
[00:38:24] [INFO] Loaded script server_scripts:hammer.js in 0.0 s
[00:38:24] [INFO] server_scripts:ore_gen_moon.js:1: Loaded Java class 'com.gregtechceu.gtceu.api.data.chemical.ChemicalHelper'
[00:38:24] [INFO] Loaded script server_scripts:ore_gen_moon.js in 0.0 s
[00:38:24] [INFO] Loaded script server_scripts:recipes_create.js in 0.001 s
[00:38:24] [INFO] Loaded script server_scripts:recipes_early_game.js in 0.0 s
[00:38:24] [INFO] Loaded script server_scripts:recipes_sequencedassembly_custom.js in 0.0 s
[00:38:24] [INFO] Loaded script server_scripts:recipe_wrapper.js in 0.001 s
[00:38:24] [INFO] server_scripts:script.js:3: Hello, World! (You will see this line every time server resources reload)
[00:38:24] [INFO] Loaded script server_scripts:script.js in 0.0 s
[00:38:24] [INFO] Loaded script server_scripts:tags.js in 0.0 s
[00:38:24] [INFO] Loaded 9/9 KubeJS server scripts in 0.016 s
[00:38:24] [INFO] Scripts loaded
[00:38:24] [INFO] Initializing recipe event...
[00:38:24] [WARN] Due to the way Minecraft resource loading works, KubeJS' server.log may not contain everything that happened in your server scripts on initial world creation.
[00:38:24] [WARN] You can still see the full log (including past reloads) in your latest.log file.
```

startup.txt
```
[00:35:24] [INIT] KubeJS 1902.6.1-build.337; MC 1902 forge
[00:35:24] [INIT] Loaded plugins:
[00:35:24] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgePlugin
[00:35:24] [INIT] - pro.mikey.kubeutils.kubejs.KubeUtilsPlugin
[00:35:24] [INIT] - com.almostreliable.ponderjs.PonderJSPlugin
[00:35:24] [INIT] - com.bobvarioa.kubejsreiruntime.integrations.kube.KubePlugin
[00:35:24] [INIT] - com.gregtechceu.gtceu.integration.kjs.GregTechKubeJSPlugin
[00:35:24] [INIT] - com.oierbravo.createmechanicalextruder.compat.kubejs.KubeJSCreateMechanicalExtruderPlugin
[00:35:24] [INIT] - dev.latvian.mods.kubejs.create.KubeJSCreatePlugin
[00:35:24] [INIT] - com.almostreliable.lootjs.kube.LootJSPlugin
[00:35:24] [INIT] - com.lowdragmc.lowdraglib.kjs.LDLibKubeJSPlugin
[00:35:24] [INIT] - com.probejs.ProbeJSPlugin
[00:35:25] [INFO] Loaded script startup_scripts:custom_blocks.js in 0.06 s
[00:35:25] [INFO] Loaded script startup_scripts:custom_items.js in 0.013 s
[00:35:25] [INFO] Loaded script startup_scripts:gt_oregen_layers.js in 0.002 s
[00:35:25] [INFO] startup_scripts:script.js:3: Hello, World! (You will only see this line once in console, during startup)
[00:35:25] [INFO] Loaded script startup_scripts:script.js in 0.001 s
[00:35:25] [INFO] Loaded 4/4 KubeJS startup scripts in 0.57 s
```

client.txt (if that might be helpful)
```
[00:35:25] [INIT] KubeJS 1902.6.1-build.337; MC 1902 forge
[00:35:25] [INIT] Loaded plugins:
[00:35:25] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgePlugin
[00:35:25] [INIT] - pro.mikey.kubeutils.kubejs.KubeUtilsPlugin
[00:35:25] [INIT] - com.almostreliable.ponderjs.PonderJSPlugin
[00:35:25] [INIT] - com.bobvarioa.kubejsreiruntime.integrations.kube.KubePlugin
[00:35:25] [INIT] - com.gregtechceu.gtceu.integration.kjs.GregTechKubeJSPlugin
[00:35:25] [INIT] - com.oierbravo.createmechanicalextruder.compat.kubejs.KubeJSCreateMechanicalExtruderPlugin
[00:35:25] [INIT] - dev.latvian.mods.kubejs.create.KubeJSCreatePlugin
[00:35:25] [INIT] - com.almostreliable.lootjs.kube.LootJSPlugin
[00:35:25] [INIT] - com.lowdragmc.lowdraglib.kjs.LDLibKubeJSPlugin
[00:35:25] [INIT] - com.probejs.ProbeJSPlugin
[00:35:25] [INFO] client_scripts:script.js:3: Hello, World! (You will see this line every time client resources reload)
[00:35:25] [INFO] Loaded script client_scripts:script.js in 0.002 s
[00:35:25] [INFO] Loaded 1/1 KubeJS client scripts in 0.036 s
```

**Comment by screret** [comment]
uh
you _sure_ that's the moon DIMENSION TYPE's id, because that's what we use for the veins because it was the easiest to access

**Comment by screret** [comment]
hm. it is.
it's trying to make a **new** dimension type for some reason.
