### ISSUE TITLE
Compatibility Issue Between gtceu and Continuity Mods

### ISSUE THREAD

**Issue by Start-Buling** [GregTechCEu/GregTechCEu-1.19#297]
### GregTech CEu Version

gtceu-fabric-1.20.1-1.0.11

### Addons Installed

- gtceu-fabric-1.20.1-1.0.11
- continuity-3.0.0-beta.2+1.20
- fabric-api-0.87.0+1.20.1

### Environment

singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

The expected behavior is to use the resourcepacks normally and have the fonts displayed correctly, rather than as blocky fonts.

### Actual Behavior

 the font becomes the wrong square garbled font, and the resourcepacks cannot be used,

### Steps to Reproduce

When installing the GTCEU and the Continuity mods, garbled characters will appear.

### Additional Information

[00:00:29] [Render thread/WARN]: Reload already ongoing, replacing
[00:00:29] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (configuration, continuity, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gtceu, ldlib, porting_lib_core, porting_lib_data, porting_lib_gametest, porting_lib_model_generators, porting_lib_model_materials, porting_lib_tags, porting_lib_utility, registrate-fabric), file/Minecraft-Mod-Language-Modpack-Converted-1.20.1.zip, ldlib
[00:00:29] [Worker-Main-13/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[00:00:29] [Worker-Main-9/WARN]: File gtceu:sounds/arc.ogg does not exist, cannot add it to event gtceu:arc
[00:00:29] [Worker-Main-9/WARN]: File gtceu:sounds/boiler.ogg does not exist, cannot add it to event gtceu:boiler
[00:00:29] [Worker-Main-11/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/stones/marble/marble_bricks_small_OG.png, ignoring
[00:00:29] [Worker-Main-11/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/multiblock/large_turbine/rotor_idle (1).png, ignoring
[00:00:29] [Worker-Main-11/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/machines/world_accelerator/OVERLAY_ACCELERATOR_ACTIVE_GLOW.png, ignoring
[00:00:29] [Worker-Main-11/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/machines/electromagnetic_separator/overlay_front_active (copy).png, ignoring
[00:00:29] [Worker-Main-11/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/cover/OVERLAY_SCREEN.png, ignoring
[00:00:30] [Worker-Main-12/WARN]: Texture gtceu:block/cover/cover_interface_computer_button with size 18x36 limits mip level from 4 to 1
[00:00:30] [Worker-Main-12/WARN]: Texture gtceu:block/cover/cover_interface_machine_off_proxy with size 14x5 limits mip level from 1 to 0
[00:00:30] [Worker-Main-12/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
[00:00:30] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class me.pepperbell.continuity.client.resource.ModelWrappingHandler
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.pepperbell.continuity.client.resource.ModelWrappingHandler
	at net.minecraft.class_1088$class_7778.localvar$zzi000$continuity$modifyBakedModel(class_1088.java:548) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_807.method_4753(class_807.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_816.method_4753(class_816.java:89) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.redirect$zfm000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:1058) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: Multiple entries with same key: ldlib:renderer_model#=Block{gtceu:luv_processing_array}[facing=east,server_tick=false] and ldlib:renderer_model#=Block{gtceu:luv_processing_array}[facing=east,server_tick=true] [in thread "Worker-Main-5"]
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:377) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:371) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:241) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:588) ~[guava-31.1-jre.jar:?]
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.createBlockStateModelIdMap(ModelWrappingHandler.java:29) ~[【链接材质mod】continuity-3.0.0-beta.2+1.20.jar:?]
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.<clinit>(ModelWrappingHandler.java:17) ~[【链接材质mod】continuity-3.0.0-beta.2+1.20.jar:?]
	at net.minecraft.class_1088$class_7778.localvar$zzi000$continuity$modifyBakedModel(class_1088.java:548) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_807.method_4753(class_807.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_816.method_4753(class_816.java:89) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.redirect$zfm000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:1058) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 6 more
[00:00:30] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (configuration, continuity, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gtceu, ldlib, porting_lib_core, porting_lib_data, porting_lib_gametest, porting_lib_model_generators, porting_lib_model_materials, porting_lib_tags, porting_lib_utility, registrate-fabric), ldlib
[00:00:30] [Worker-Main-11/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[00:00:30] [Worker-Main-12/WARN]: File gtceu:sounds/arc.ogg does not exist, cannot add it to event gtceu:arc
[00:00:30] [Worker-Main-12/WARN]: File gtceu:sounds/boiler.ogg does not exist, cannot add it to event gtceu:boiler
[00:00:30] [Worker-Main-10/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/stones/marble/marble_bricks_small_OG.png, ignoring
[00:00:30] [Worker-Main-10/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/multiblock/large_turbine/rotor_idle (1).png, ignoring
[00:00:30] [Worker-Main-10/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/machines/world_accelerator/OVERLAY_ACCELERATOR_ACTIVE_GLOW.png, ignoring
[00:00:30] [Worker-Main-10/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/machines/electromagnetic_separator/overlay_front_active (copy).png, ignoring
[00:00:30] [Worker-Main-10/ERROR]: Invalid path in mod resource-pack gtceu: gtceu:textures/block/cover/OVERLAY_SCREEN.png, ignoring
[00:00:30] [Worker-Main-14/WARN]: Texture gtceu:block/cover/cover_interface_computer_button with size 18x36 limits mip level from 4 to 1
[00:00:30] [Worker-Main-14/WARN]: Texture gtceu:block/cover/cover_interface_machine_off_proxy with size 14x5 limits mip level from 1 to 0
[00:00:30] [Worker-Main-14/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
[00:00:33] [Render thread/INFO]: Stopping!
[00:00:33] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:174) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1138) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:266) ~[1.20.1%e6%b5%8b%e8%af%95.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]

**Comment by Yefancy** [comment]
report to continuity

**Comment by Start-Buling** [comment]
Alright, I have already submitted this issue to them. Thank you for your response.
