### ISSUE TITLE
NullPointerException when Rendering Overlay due to Missing minecraft:water Registry Object

### ISSUE THREAD

**Issue by pen787** [GregTechCEu/GregTechCEu-1.19#438]
### GregTech CEu Version

1.0.12.g-build_216

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Not crash.

### Actual Behavior

Crash.

### Steps to Reproduce

1. Start a minecraft

### Additional Information

[raw_crash_log.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12779761/raw.txt)
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-10-02 11:56:54
Description: Rendering overlay

java.lang.NullPointerException: Registry Object not present: minecraft:water
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.3.0-universal.jar%23318!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.common.ForgeHooks.getVanillaFluidType(ForgeHooks.java:960) ~[forge-1.19.2-43.3.0-universal.jar%23318!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.level.material.Fluid.getFluidType(Fluid.java:108) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinFluid,pl:mixin:APP:architectury-common.mixins.json:inject.MixinFluid,pl:mixin:A}
	at net.minecraftforge.client.extensions.common.IClientFluidTypeExtensions.of(IClientFluidTypeExtensions.java:57) ~[forge-1.19.2-43.3.0-universal.jar%23318!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.gregtechceu.gtceu.core.forge.MixinHelpersImpl.addFluidTexture(MixinHelpersImpl.java:12) ~[gtceu-forge-1.19.2-1.0.12.g-build_216.jar%23270!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.gregtechceu.gtceu.core.MixinHelpers.addFluidTexture(MixinHelpers.java) ~[gtceu-forge-1.19.2-1.0.12.g-build_216.jar%23270!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.resources.model.ModelBakery.redirect$zma000$gtceu$injectModelBakery(ModelBakery.java:660) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:moonlight.mixins.json:ConditionsHackMixin,pl:mixin:APP:forge-immediatelyfast-common.mixins.json:fast_text_lookup.ISinglePreparationResourceReloader,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:forge-immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:forge-immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23313!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.0.jar%23152!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23139!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23139!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23139!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23139!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23139!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23139!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23139!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58) [ForgeWrapper-1.5.6-prism.jar:1.5.6-prism] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, quark-emote-pack, KubeJS Resource Pack [assets], kubejs

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 272926592 bytes (260 MiB) / 931135488 bytes (888 MiB) up to 6392119296 bytes (6096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 17 Stepping 0
	Microarchitecture: Zen
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1070 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2698
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25548.48
	Virtual memory used (MB): 15277.55
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 520.10
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6096m
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 526.98, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		saturn-mc1.19.2-0.0.4.jar                         |Saturn                        |saturn                        |0.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |COMMON_SET|Manifest: NOSIGNATURE
		rhino-forge-1902.2.2-build.272.jar                |Rhino                         |rhino                         |1902.2.2-build.272  |COMMON_SET|Manifest: NOSIGNATURE
		notenoughcrashes-4.2.1+1.19.2-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.2.1+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		kube-utils-forge-1.0.3+mc1.19.2.jar               |KubeUtils                     |kubeutils                     |1.0.3+mc1.19.2      |COMMON_SET|Manifest: NOSIGNATURE
		jmi-forge-1.19.2-0.13-44.jar                      |JourneyMap Integration        |jmi                           |0.13-44             |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-mc1.19.2-0.6.2c.jar                      |Rubidium                      |rubidium                      |0.6.2c              |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.4.1.jar                 |Waystones                     |waystones                     |11.4.1              |COMMON_SET|Manifest: NOSIGNATURE
		FastSuite-1.19.2-4.1.1.jar                        |Fast Suite                    |fastsuite                     |4.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+14.jar                  |Clumps                        |clumps                        |9.0.0+14            |COMMON_SET|Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.19.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.19.2-10.0+7.jar               |Controlling                   |controlling                   |10.0+7              |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.19.2-7.3.3.jar                          |Placebo                       |placebo                       |7.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		modernfix-forge-5.7.4+mc1.19.2.jar                |ModernFix                     |modernfix                     |5.7.4+mc1.19.2      |COMMON_SET|Manifest: NOSIGNATURE
		REIPluginCompatibilities-forge-9.0.84.jar         |REI Plugin Compatibilities    |rei_plugin_compatibilities    |9.0.84              |COMMON_SET|Manifest: NOSIGNATURE
		artifacts-1.19.2-5.0.4.jar                        |Artifacts                     |artifacts                     |1.19.2-5.0.4        |COMMON_SET|Manifest: NOSIGNATURE
		configured-2.1.1-1.19.2.jar                       |Configured                    |configured                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-rc.2.jar                  |MixinExtras                   |mixinextras                   |0.2.0-rc.2          |COMMON_SET|Manifest: NOSIGNATURE
		gtceu-forge-1.19.2-1.0.12.g-build_216.jar         |GregTech                      |gtceu                         |1.0.12.g-build_216  |COMMON_SET|Manifest: NOSIGNATURE
		lazydfu-1.19-1.0.2.jar                            |LazyDFU                       |lazydfu                       |0.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		starlight-1.1.1+forge.cf5b10b.jar                 |Starlight                     |starlight                     |1.1.1+forge.a3aea74 |COMMON_SET|Manifest: NOSIGNATURE
		everycomp-1.19.2-2.5.7.jar                        |Every Compat                  |everycomp                     |1.19.2-2.5.7        |COMMON_SET|Manifest: NOSIGNATURE
		ldlib-forge-1.19.2-1.0.19.d.jar                   |LowDragLib                    |ldlib                         |1.0.19.d            |COMMON_SET|Manifest: NOSIGNATURE
		farsight-1.19.2-3.5.jar                           |Farsight mod                  |farsight_view                 |1.19.2-3.5          |ERROR     |Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.6.0.jar                       |Balm                          |balm                          |4.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		carryon-forge-1.19.2-2.1.1.21.jar                 |Carry On                      |carryon                       |2.1.1.21            |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-8.3.103-forge.jar                    |Cloth Config v8 API           |cloth_config                  |8.3.103             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.3.0-universal.jar                 |Forge                         |forge                         |43.3.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		corpse-1.19.2-1.0.0.jar                           |Corpse                        |corpse                        |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		craftingtweaks-forge-1.19.2-15.1.8.jar            |CraftingTweaks                |craftingtweaks                |15.1.8              |COMMON_SET|Manifest: NOSIGNATURE
		tectonic-mod-mc1.19.2-v2.1.1.jar                  |Tectonic                      |tectonic                      |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TerraBlender-forge-1.19.2-2.0.1.166.jar           |TerraBlender                  |terrablender                  |2.0.1.166           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.46-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.46       |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                |COMMON_SET|Manifest: NOSIGNATURE
		configuration-444699-4519560.jar                  |Configuration                 |configuration                 |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		titanium-1.19.2-3.7.3-27.jar                      |Titanium                      |titanium                      |3.7.3               |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.2-17.1.2.544.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.2.544          |COMMON_SET|Manifest: NOSIGNATURE
		tectonicbop-1.19.2-Beta3.jar                      |Tectonic for Biomes O' Plenty |tectonicbop                   |1.1.9b              |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.9.0.jar                       |Jade                          |jade                          |8.9.0               |COMMON_SET|Manifest: NOSIGNATURE
		appliedenergistics2-forge-12.9.8.jar              |Applied Energistics 2         |ae2                           |12.9.8              |COMMON_SET|Manifest: NOSIGNATURE
		another_furniture-forge-1.19.2-2.1.4.jar          |Another Furniture             |another_furniture             |1.19.2-2.1.4        |COMMON_SET|Manifest: NOSIGNATURE
		spark-1.10.37-forge.jar                           |spark                         |spark                         |1.10.37             |COMMON_SET|Manifest: NOSIGNATURE
		pipez-1.19.2-1.1.5.jar                            |Pipez                         |pipez                         |1.19.2-1.1.5        |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.10-20.jar               |Flywheel                      |flywheel                      |0.6.10-20           |COMMON_SET|Manifest: NOSIGNATURE
		create-1.19.2-0.5.1.e.jar                         |Create                        |create                        |0.5.1.e             |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |COMMON_SET|Manifest: NOSIGNATURE
		Quark-3.4-409.jar                                 |Quark                         |quark                         |3.4-409             |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.3.24.jar                 |Supplementaries               |supplementaries               |1.19.2-2.3.24       |COMMON_SET|Manifest: NOSIGNATURE
		suppsquared-1.19.2-1.1.1.jar                      |Supplementaries Squared       |suppsquared                   |1.19.2-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		almostunified-forge-1.19.2-0.7.0.jar              |AlmostUnified                 |almostunified                 |1.19.2-0.7.0        |COMMON_SET|Manifest: NOSIGNATURE
		RoughlyEnoughItems-9.1.663.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |9.1.663             |COMMON_SET|Manifest: NOSIGNATURE
		entityculling-forge-1.6.1-mc1.19.2.jar            |EntityCulling                 |entityculling                 |1.6.1               |COMMON_SET|Manifest: NOSIGNATURE
		canary-mc1.19.2-0.2.8.jar                         |Canary                        |canary                        |0.2.8               |COMMON_SET|Manifest: NOSIGNATURE
		ImmediatelyFast-1.2.5+1.19.2.jar                  |ImmediatelyFast               |immediatelyfast               |1.2.5+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		pluto-mc1.19.2-0.0.9.jar                          |Pluto                         |pluto                         |0.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		lootjs-forge-1.19.2-2.9.1.jar                     |LootJS                        |lootjs                        |2.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |COMMON_SET|Manifest: NOSIGNATURE
		kubejs-forge-1902.6.2-build.15.jar                |KubeJS                        |kubejs                        |1902.6.2-build.15   |COMMON_SET|Manifest: NOSIGNATURE
		AE2WTLib-12.9.7.jar                               |AE2WTLib                      |ae2wtlib                      |12.9.7              |COMMON_SET|Manifest: NOSIGNATURE
		ftb-library-forge-1902.4.1-build.236.jar          |FTB Library                   |ftblibrary                    |1902.4.1-build.236  |COMMON_SET|Manifest: NOSIGNATURE
		item-filters-forge-1902.2.9-build.51.jar          |Item Filters                  |itemfilters                   |1902.2.9-build.51   |COMMON_SET|Manifest: NOSIGNATURE
		kubejsadditions-forge-3.2.0.jar                   |KubeJS Addditions (Forge)     |kubejsadditions               |3.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		ponderjs-1.19.2-1.2.0.jar                         |PonderJS                      |ponderjs                      |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		rer-2.6.1.jar                                     |Roughly Enough Resources      |roughlyenoughresources        |2.6.1               |COMMON_SET|Manifest: NOSIGNATURE
		ftb-teams-forge-1902.2.14-build.123.jar           |FTB Teams                     |ftbteams                      |1902.2.14-build.123 |COMMON_SET|Manifest: NOSIGNATURE
		ftb-chunks-forge-1902.4.2-build.302.jar           |FTB Chunks                    |ftbchunks                     |1902.4.2-build.302  |COMMON_SET|Manifest: NOSIGNATURE
		kubejsoffline-2.1.6.jar                           |KubeJS Offline (Forge)        |kubejsoffline                 |2.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		ftb-quests-forge-1902.5.5-build.297.jar           |FTB Quests                    |ftbquests                     |1902.5.5-build.297  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-ranks-forge-1902.1.15-build.77.jar            |FTB Ranks                     |ftbranks                      |1902.1.15-build.77  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-essentials-forge-1902.3.3-build.100.jar       |FTB Essentials                |ftbessentials                 |1902.3.3-build.100  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-xmod-compat-forge-1.2.2.jar                   |FTB XMod Compat               |ftbxmodcompat                 |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		kubejs-create-forge-1902.2.4-build.29.jar         |KubeJS Create                 |kubejs_create                 |1902.2.4-build.29   |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		cc-tweaked-1.19.2-1.101.3.jar                     |CC: Tweaked                   |computercraft                 |1.101.3             |COMMON_SET|Manifest: NOSIGNATURE
		functionalstorage-1.19.2-1.1.7.jar                |Functional Storage            |functionalstorage             |1.19.2-1.1.7        |COMMON_SET|Manifest: NOSIGNATURE
		JadeAddons-1.19.2-forge-3.5.0.jar                 |Jade Addons                   |jadeaddons                    |3.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		probejs-5.3.1-forge.jar                           |ProbeJS                       |probejs                       |5.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		polylib-forge-1900.0.2-build.73.jar               |PolyLib                       |polylib                       |1900.0.2-build.73   |COMMON_SET|Manifest: NOSIGNATURE
		ftbbackups2-forge-1.19.2-1.0.22.jar               |FTB Backups 2                 |ftbbackups2                   |1.0.22              |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |COMMON_SET|Manifest: NOSIGNATURE
		expandability-forge-7.0.0.jar                     |ExpandAbility                 |expandability                 |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		createaddition-1.19.2-1.1.1.jar                   |Create Crafts & Additions     |createaddition                |1.19.2-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 817c684c-3b70-4aac-bbdf-15c69e1474b1
	FML: 43.3
	Forge: net.minecraftforge:43.3.0
	Flywheel Backend: Uninitialized
	Suspected Mods: GregTech (gtceu)
```

**Comment by mikerooni** [comment]
This also causes a crash on startup when the latest version of Create is installed.

**Comment by screret** [comment]
latest.log?

**Comment by pen787** [comment]
It's long gone.

**Comment by screret** [comment]
well the issue would've been identifiable from the latest.log
