### ISSUE TITLE
Crash when running on dedicated server

### ISSUE THREAD

**Issue by gundami** [GregTechCEu/GregTechCEu-1.19#44]
### GregTech CEu Version

v1.0.2

### Recipe Viewer Installed

None

### Environment

Dedicated server

### Cross-Mod Interaction

Yes

### Expected Behavior

start server

### Actual Behavior

crash on during start

### Steps to Reproduce

server log: https://paste.ubuntu.com/p/tv6khxnXRK/

**Comment by gundami** [comment]
mod can be loaded now, but server will crash when place machine block.
`java.lang.ExceptionInInitializerError: null
        at com.gregtechceu.gtceu.api.machine.steam.SteamWorkableMachine.createRecipeLogic(SteamWorkableMachine.java:97) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.api.machine.steam.SteamWorkableMachine.<init>(SteamWorkableMachine.java:64) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.api.machine.steam.SteamBoilerMachine.<init>(SteamBoilerMachine.java:69) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.common.machine.steam.SteamLiquidBoilerMachine.<init>(SteamLiquidBoilerMachine.java:41) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.common.data.GTMachines.lambda$static$8(GTMachines.java:111) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.common.data.GTMachines.lambda$registerSteamMachines$79(GTMachines.java:732) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.api.machine.MachineDefinition.createMetaMachine(MachineDefinition.java:90) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.api.blockentity.MetaMachineBlockEntity.<init>(MetaMachineBlockEntity.java:32) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.api.blockentity.fabric.MetaMachineBlockEntityImpl.<init>(MetaMachineBlockEntityImpl.java:29) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.api.blockentity.fabric.MetaMachineBlockEntityImpl.createBlockEntity(MetaMachineBlockEntityImpl.java:33) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.api.blockentity.MetaMachineBlockEntity.createBlockEntity(MetaMachineBlockEntity.java) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.gregtechceu.gtceu.api.registry.registrate.MachineBuilder.lambda$register$21(MachineBuilder.java:224) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at com.tterrag.registrate.builders.BlockEntityBuilder.lambda$createEntry$2(BlockEntityBuilder.java:131) ~[registrate-fabric-1.1.50-MC1.19.2-1492de817610234d.jar:?]
        at net.minecraft.class_2591.method_11032(class_2591.java:86) ~[server-intermediary.jar:?]
        at com.gregtechceu.gtceu.api.block.IMachineBlock.method_10123(IMachineBlock.java:46) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        at net.minecraft.class_2818.method_12010(class_2818.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_30092(class_1937.java:221) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8652(class_1937.java:206) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7708(class_1747.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7712(class_1747.java:76) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7884(class_1747.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.method_7981(class_1799.java:264) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.redirect$bbj000$factions$place(class_3225.java:2019) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:355) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1145) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: Cannot load class com.gregtechceu.gtceu.api.sound.AutoReleasedSound in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
        at java.lang.Class.getDeclaredFields(Unknown Source) ~[?:?]
        at com.lowdragmc.lowdraglib.syncdata.ManagedFieldUtils.getManagedFields(ManagedFieldUtils.java:23) ~[ldlib-fabric-1.19.2-1.0.4.c.jar:?]
        at com.lowdragmc.lowdraglib.syncdata.field.ManagedFieldHolder.initAll(ManagedFieldHolder.java:47) ~[ldlib-fabric-1.19.2-1.0.4.c.jar:?]
        at com.lowdragmc.lowdraglib.syncdata.field.ManagedFieldHolder.<init>(ManagedFieldHolder.java:22) ~[ldlib-fabric-1.19.2-1.0.4.c.jar:?]
        at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.<clinit>(RecipeLogic.java:29) ~[gtceu-fabric-1.19.2-1.0.2.jar:?]
        ... 41 more`
