### ISSUE TITLE
Nbt data lost in irregular interval

### ISSUE THREAD

**Issue by Nebdir** [GregTechCEu/GregTechCEu-1.19#442]
### GregTech CEu Version

1.0.12g

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Machines keep their inventories

### Actual Behavior

On some points the game failes to load nbt date ( read from log output ) 
I suspect this might be related  to migration from version to version.

Machine inventory are voided, sometimes goes hand in hand with a chrash. but im not shure if these are that much related...

### Steps to Reproduce

1. Start singleplayer world (first time created with ~1.0.10??)
2. game chrashed a few times
3. upgrade gregtech and other mods (sodium, indium, fabric api... no content mods available)
4. since 1.0.12g bug appears
5. moving 12k thought nether to new place
6. bug appears

### Additional Information

recent stacktraces and chrashes:

```
[09:33:44] [Render thread/INFO]: Stopping worker threads
[09:33:44] [Render thread/INFO]: Started 10 worker threads
[09:33:44] [Render thread/INFO]: Stopping worker threads
[09:33:44] [Render thread/INFO]: Started 10 worker threads
[09:33:44] [Render thread/INFO]: Stopping worker threads
[09:33:44] [Render thread/INFO]: Started 10 worker threads
[09:33:45] [Server thread/ERROR]: Failed to load data for block entity gtceu:coke_oven
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:618) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.ingredient.FluidIngredient.fromNetwork(FluidIngredient.java:148) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:30) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:17) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.IContentSerializer.fromNetworkContent(IContentSerializer.java:43) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:231) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.entryReader(GTRecipeSerializer.java:86) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.fromNetwork(GTRecipeSerializer.java:120) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:36) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:18) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.CustomObjectAccessor.writeManagedField(CustomObjectAccessor.java:62) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ManagedAccessor.writeField(ManagedAccessor.java:52) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writeToReadonlyField(IManagedAccessor.java:120) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ReadonlyAccessor.writeField(ReadonlyAccessor.java:85) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.blockentity.IAutoPersistBlockEntity.loadManagedPersistentData(IAutoPersistBlockEntity.java:35) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at net.minecraft.class_2586.handler$bed000$ldlib$injectLoad(class_2586.java:1544) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_11014(class_2586.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_17897(class_2586.java:132) ~[client-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_2586.method_11005(class_2586.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_39797(class_2852.java:408) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:751) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:739) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Invalid tag id: -128
	at net.minecraft.class_4614$1.method_39878(class_4614.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23264(class_4614.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23262(class_4614.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[client-intermediary.jar:?]
	... 50 more
[09:33:45] [Server thread/WARN]: Skipping BlockEntity with id gtceu:coke_oven
[09:35:24] [Render thread/INFO]: [System] [CHAT] [Debug]: Key bindings:
``` 

```

[07:48:35] [Render thread/INFO]: Started 10 worker threads
[07:48:35] [Server thread/ERROR]: Failed to load data for block entity gtceu:lv_steam_turbine
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:618) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.ingredient.FluidIngredient.fromNetwork(FluidIngredient.java:148) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:30) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:17) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.IContentSerializer.fromNetworkContent(IContentSerializer.java:43) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:231) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.entryReader(GTRecipeSerializer.java:86) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.fromNetwork(GTRecipeSerializer.java:118) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:36) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:18) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.CustomObjectAccessor.writeManagedField(CustomObjectAccessor.java:62) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ManagedAccessor.writeField(ManagedAccessor.java:52) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writeToReadonlyField(IManagedAccessor.java:120) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ReadonlyAccessor.writeField(ReadonlyAccessor.java:85) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.blockentity.IAutoPersistBlockEntity.loadManagedPersistentData(IAutoPersistBlockEntity.java:35) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at net.minecraft.class_2586.handler$bed000$ldlib$injectLoad(class_2586.java:1544) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_11014(class_2586.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_17897(class_2586.java:132) ~[client-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_2586.method_11005(class_2586.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_39797(class_2852.java:408) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:751) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:739) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Invalid tag id: -128
	at net.minecraft.class_4614$1.method_39878(class_4614.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23264(class_4614.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23262(class_4614.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[client-intermediary.jar:?]
	... 50 more
[07:48:35] [Server thread/WARN]: Skipping BlockEntity with id gtceu:lv_steam_turbine
[07:48:35] [Server thread/ERROR]: Failed to load data for block entity gtceu:lv_chemical_reactor
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:618) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.ingredient.FluidIngredient.fromNetwork(FluidIngredient.java:148) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:30) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:17) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.IContentSerializer.fromNetworkContent(IContentSerializer.java:43) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:231) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.entryReader(GTRecipeSerializer.java:86) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.fromNetwork(GTRecipeSerializer.java:120) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:36) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:18) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.CustomObjectAccessor.writeManagedField(CustomObjectAccessor.java:62) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ManagedAccessor.writeField(ManagedAccessor.java:52) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writeToReadonlyField(IManagedAccessor.java:120) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ReadonlyAccessor.writeField(ReadonlyAccessor.java:85) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.blockentity.IAutoPersistBlockEntity.loadManagedPersistentData(IAutoPersistBlockEntity.java:35) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at net.minecraft.class_2586.handler$bed000$ldlib$injectLoad(class_2586.java:1544) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_11014(class_2586.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_17897(class_2586.java:132) ~[client-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_2586.method_11005(class_2586.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_39797(class_2852.java:408) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:751) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:739) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Invalid tag id: -128
	at net.minecraft.class_4614$1.method_39878(class_4614.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23264(class_4614.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23262(class_4614.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[client-intermediary.jar:?]
	... 50 more
[07:48:35] [Server thread/WARN]: Skipping BlockEntity with id gtceu:lv_chemical_reactor
[07:52:42] [Render thread/INFO]: Reloading pipeline on dimension change: NamespacedId{namespace='minecraft', name='overworld'} => NamespacedId{namespace='minecraft', name='the_nether'}
[07:52:42] [Render thread/INFO]: Destroying pipeline NamespacedId{namespace='minecraft', name='overworld'}
``` 

```

[08:10:33] [Render thread/INFO]: Loaded 553 advancements
[08:10:36] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:old_growth_birch_forest]=net.minecraft.class_1959@e6c020f}]
	at net.minecraft.class_7510.method_44210(class_7510.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_44215(class_2794.java:102) ~[client-intermediary.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[08:10:36] [Server thread/ERROR]: This crash report has been saved to: <SNIP>/PrismLauncher/instances/greg's n'd tool's/.minecraft/crash-reports/crash-2023-10-03_08.10.36-server.txt
[08:10:36] [Server thread/INFO]: Stopping server
```

**Comment by screret** [comment]
the fluid ingredient issue will be fixed on next release.
